logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
spring:
  r2dbc:
    name: todo_db
    url: r2dbc:postgresql://localhost:5434
    username: root  # change from root in future
    password: password
  datasource:
    initialization-mode: always

