version: '3.8'

services:

    db:
        container_name: todo_db_container
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: todo_db
        ports:
            - "5434:5432"
        volumes:
            - db-data:/var/lib/postgresql/data

volumes:
    db-data:
        name: todo_db_container_data
        external: false
